host: 34.218.210.232
user: riteshkarvaloc
token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImExNmE0NjQ3NTYyZDg2NjYzYmY2OTRlNTBjY2FmYzNiZGYwNTVkYTMifQ.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjU1NTYvZGV4Iiwic3ViIjoiQ2c1eWFYUmxjMmhyWVhKMllXeHZZeElHWjJsMGFIVmkiLCJhdWQiOiJka3ViZSIsImV4cCI6MTU4ODMxMjkwNCwiaWF0IjoxNTg4MDUzNzA0LCJhenAiOiJka3ViZSIsImF0X2hhc2giOiJiSEtBbEtMRHF6ZE5PbGdESTlQN1RBIiwibmFtZSI6InJpdGVzaGthcnZhbG9jIiwicHJlZmVycmVkX3VzZXJuYW1lIjoicml0ZXNoa2FydmFsb2MiLCJmZWRlcmF0ZWRfY2xhaW1zIjp7ImNvbm5lY3Rvcl9pZCI6ImdpdGh1YiIsInVzZXJfaWQiOiJyaXRlc2hrYXJ2YWxvYyJ9fQ.FJLGuJrQbcQzWKQyQ3RjLIP7PBpyr5oOa0Omh4drtaAPgnB6L6K5giKVrFOhjMThw27ceminuk7OFyXnJNXMwtS0YauckLEKQytwe01rfkXEDxVepSSueE-coeQ86z1nWbuVw5n1hc7bEyDLmGlCUAN3jhN-zAZznGWvg3EjDXi9NdMg__nj4UwUOOBCFGjrSKmBhDjWp5qUwPk0w2L2CZzfAOsVKXaq_aHE3rPLkoV8nwSoZ9lF9YSlpHy3N2Q9O-KS1-TJobodAGjtit7AVOeqBiD5KDT6TOMar8gGyRuawCaXOeDrHLr4J4HoMbNOrP1uuroAP40UiPnaGaPAFQ
jobname: auto
workspace: mnist-digits
script: python model.py
datasets:
  - name: mnist-digits
    mountpath: /opt/dkube/input
models:
  - mnist-digits
